export const siteConfig = {
  name: "MECNUN // Creative Engineering & 3D WebGL Studio",
  shortName: "MECNUN",
  description:
    "Computer engineer creating modern websites, Next.js full-stack web applications, technical SEO architecture, and interactive 3D WebGL experiences for ambitious brands.",
  url: "https://mecnun.dev",
  ogImage: "https://mecnun.dev/og.jpg",
  creator: "Tayfur Parmak",
  keywords: [
    "Computer Engineer",
    "Web Developer",
    "Creative Technology",
    "Next.js 14 App Router",
    "React Three Fiber",
    "Three.js 3D WebGL",
    "Technical SEO Architecture",
    "Core Web Vitals",
    "Headless Commerce Shopify",
    "Editorial Web Design",
    "TypeScript",
    "GSAP ScrollTrigger",
    "Performance Optimization",
  ],
  author: {
    name: "Tayfur Parmak",
    role: "Computer Engineer & Web Developer",
    url: "https://mecnun.dev/about",
    sameAs: [
      "https://github.com/mecnundev-glitch",
      "https://linkedin.com/in/tayfurparmak",
      "https://twitter.com/mecnundev",
    ],
  },
  organization: {
    name: "MECNUN Studio",
    legalName: "Mecnun Creative Engineering",
    url: "https://mecnun.dev",
    logo: "https://mecnun.dev/brand/logo.png",
    foundingDate: "2024",
    email: "contact@mecnunum.com",
    address: {
      addressLocality: "Istanbul",
      addressCountry: "TR",
    },
  },
  links: {
    twitter: "https://twitter.com/mecnundev",
    github: "https://github.com/mecnundev-glitch/mecnunum",
    linkedin: "https://linkedin.com/in/tayfurparmak",
    instagram: "https://instagram.com/mecnunum",
    email: "mailto:contact@mecnunum.com",
  },
};
